language: java
sudo: false
install: ""
script: ./gradlew clean check
branches:
    only:
        - master
jdk:
    - oraclejdk8
cache:
    directories:
        - $HOME/.gradle/caches
        - $HOME/.gradle/wrapper
