language: java
sudo: false
install: ""
script: ./travis.sh
branches:
    only:
        - master
jdk:
    - oraclejdk8
cache:
    directories:
        - $HOME/.gradle/caches
        - $HOME/.gradle/wrapper
